name: Publish Image to Docker Hub

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Parse tag name
      run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)" >> $GITHUB_ENV

    # Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push to Docker Hub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ env.TAG_NAME }}

    # Login to AWS ECR
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Push to Docker Hub and AWS ECR
    - name: Push to AWS ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-auth-service:latest,${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-auth-service:${{ env.TAG_NAME }}

    # SecureCN Scan
    - name: Scan image
      run: curl -L -s https://securecn.cisco.com/tools/cli/portshift_deployment_cli > scan && chmod +x scan && ./scan run-vulnerability-scan --access-key ${{ secrets.SECURECN_ACCESS_KEY }} --secret-key ${{ secrets.SECURECN_SECRET_KEY }} --image-name=${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/bbk-auth-service:${{ env.TAG_NAME }}
